### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by VaghehDashti** [radinhamidi/Team_Formation_Library#4]
I tried to run your code with the dataset that you have provided, but it throws an error when training starts:
`
Beginning Step#3: Train/Test Data Split
[19564  2799 22513 ... 13927   919 10742]
[ 8138 17918 19284 ... 15263 15164 30127]
Train/test data split is complete.

Beginning Step#4: VAE Training/Testing
Input/output Dimensions:   1 1
2021-09-05 20:49:32.882585: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-09-05 20:49:32.884841: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-09-05 20:49:32.887016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-09-05 20:49:32.889368: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-09-05 20:49:32.890854: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-09-05 20:49:32.892216: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
2021-09-05 20:49:32.893566: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-09-05 20:49:32.894929: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-09-05 20:49:32.895113: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-09-05 20:49:32.895827: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
encoder_input (InputLayer)      [(None, 1)]          0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 1)            2           encoder_input[0][0]              
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            4           dense[0][0]                      
__________________________________________________________________________________________________
z_log_var (Dense)               (None, 2)            4           dense[0][0]                      
__________________________________________________________________________________________________
z (Lambda)                      (None, 2)            0           z_mean[0][0]                     
                                                                 z_log_var[0][0]                  
==================================================================================================
Total params: 10
Trainable params: 10
Non-trainable params: 0
__________________________________________________________________________________________________
Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
z_sampling (InputLayer)      [(None, 2)]               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 2         
=================================================================
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Model: "vae_mlp"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
encoder_input (InputLayer)   [(None, 1)]               0         
_________________________________________________________________
encoder (Functional)         [(None, 2), (None, 2), (N 10        
_________________________________________________________________
decoder (Functional)         (None, 1)                 5         
=================================================================
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
2021-09-05 20:49:33.100814: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/2000
WARNING:tensorflow:Model was constructed with shape (None, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='encoder_input'), name='encoder_input', description="created by layer 'encoder_input'"), but it was called on an input with incompatible shape (None, 1, 2000).
WARNING:tensorflow:Model was constructed with shape (None, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='encoder_input'), name='encoder_input', description="created by layer 'encoder_input'"), but it was called on an input with incompatible shape (None, 1, 2000).
Traceback (most recent call last):
  File "C:/Users/Arman/Projects/Team_Formation_Library-master/Team_Formation_Library-master/teamFormationLibrary/example.py", line 41, in <module>
    main_team_formation()
  File "C:/Users/Arman/Projects/Team_Formation_Library-master/Team_Formation_Library-master/teamFormationLibrary/example.py", line 36, in main_team_formation
    TFL.generate_VAE()
  File "C:\Users\Arman\Projects\Team_Formation_Library-master\Team_Formation_Library-master\teamFormationLibrary\TFL.py", line 147, in generate_VAE
    vae.vae_training()  # train the VAE model
  File "C:\Users\Arman\Projects\Team_Formation_Library-master\Team_Formation_Library-master\teamFormationLibrary\VAE.py", line 116, in vae_training
    self.variational_autoencoder.fit(self.x_train, self.y_train,
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:853 train_function  *
        return step_function(self, iterator)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:835 run_step  **
        outputs = model.train_step(data)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:787 train_step
        y_pred = self(x, training=True)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\functional.py:414 call
        return self._run_internal_graph(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\functional.py:550 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\functional.py:414 call
        return self._run_internal_graph(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\functional.py:550 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\base_layer.py:1020 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\input_spec.py:250 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer dense is incompatible with the layer: expected axis -1 of input shape to have value 1 but received input with shape (None, 1, 2000)

****
`

**Comment by VaghehDashti** [comment]
I cloned the code again and tried to run with the dataset you provided:

Beginning Step#3: Train/Test Data Split
[19564  2799 22513 ... 13927   919 10742]
[ 8138 17918 19284 ... 15263 15164 30127]
Train/test data split is complete.

Beginning Step#4: VAE Training/Testing
Input/output Dimensions:   100 2470
2021-10-05 19:27:47.949641: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-05 19:27:47.951803: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-10-05 19:27:47.953908: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-10-05 19:27:47.955535: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-10-05 19:27:47.956792: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-10-05 19:27:47.958047: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
2021-10-05 19:27:47.959366: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-10-05 19:27:47.960606: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-10-05 19:27:47.960780: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-10-05 19:27:47.961438: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Model: "encoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
encoder_input (InputLayer)      [(None, 100)]        0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 100)          10100       encoder_input[0][0]              
__________________________________________________________________________________________________
z_mean (Dense)                  (None, 2)            202         dense[0][0]                      
__________________________________________________________________________________________________
z_log_var (Dense)               (None, 2)            202         dense[0][0]                      
__________________________________________________________________________________________________
z (Lambda)                      (None, 2)            0           z_mean[0][0]                     
                                                                 z_log_var[0][0]                  
==================================================================================================
Total params: 10,504
Trainable params: 10,504
Non-trainable params: 0
__________________________________________________________________________________________________
Model: "decoder"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
z_sampling (InputLayer)      [(None, 2)]               0         
_________________________________________________________________
dense_1 (Dense)              (None, 2470)              7410      
_________________________________________________________________
dense_2 (Dense)              (None, 2470)              6103370   
=================================================================
Total params: 6,110,780
Trainable params: 6,110,780
Non-trainable params: 0
_________________________________________________________________
Model: "vae_mlp"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
encoder_input (InputLayer)   [(None, 100)]             0         
_________________________________________________________________
encoder (Functional)         [(None, 2), (None, 2), (N 10504     
_________________________________________________________________
decoder (Functional)         (None, 2470)              6110780   
=================================================================
Total params: 6,121,284
Trainable params: 6,121,284
Non-trainable params: 0
_________________________________________________________________
2021-10-05 19:27:48.266250: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/2000
Traceback (most recent call last):
  File "C:/Users/Arman/Projects/Team_Formation_Library/teamFormationLibrary/example.py", line 43, in <module>
    main_team_formation()
  File "C:/Users/Arman/Projects/Team_Formation_Library/teamFormationLibrary/example.py", line 38, in main_team_formation
    TFL.generate_VAE()
  File "C:\Users\Arman\Projects\Team_Formation_Library\teamFormationLibrary\TFL.py", line 147, in generate_VAE
    vae.vae_training()  # train the VAE model
  File "C:\Users\Arman\Projects\Team_Formation_Library\teamFormationLibrary\VAE.py", line 116, in vae_training
    self.variational_autoencoder.fit(self.x_train, self.y_train,
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\eager\def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:853 train_function  *
        return step_function(self, iterator)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:842 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:835 run_step  **
        outputs = model.train_step(data)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\training.py:788 train_step
        loss = self.compiled_loss(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\compile_utils.py:239 __call__
        self._loss_metric.update_state(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\utils\metrics_utils.py:73 decorated
        update_op = update_state_fn(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\metrics.py:177 update_state_fn
        return ag_update_state(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\metrics.py:409 update_state  **
        sample_weight = tf.__internal__.ops.broadcast_weights(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\ops\weights_broadcast_ops.py:157 broadcast_weights
        values = ops.convert_to_tensor(values, name="values")
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\profiler\trace.py:163 wrapped
        return func(*args, **kwargs)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\constant_op.py:271 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\constant_op.py:288 _constant_impl
        tensor_util.make_tensor_proto(
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\tensorflow\python\framework\tensor_util.py:435 make_tensor_proto
        values = np.asarray(values)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\numpy\core\_asarray.py:83 asarray
        return array(a, dtype, copy=False, order=order)
    C:\Users\Arman\anaconda3\envs\tfl\lib\site-packages\keras\engine\keras_tensor.py:244 __array__
        raise TypeError(

    TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.

**Comment by VaghehDashti** [comment]
I was able to fix the problem by adding:

from tensorflow.python.framework.ops import disable_eager_execution

disable_eager_execution()

to the beginning of the VAE.py
